CREATE TABLE 'one_board' (
    'IDX' int(11) NOT NULL AUTO_INCREMENT,
    'PRE_IDX' int(11) DEFAULT NULL,
    'TITLE' varchar(100) NOT NULL,
    'CONTENTS' varchar(4000) NOT NULL,
    'HIT_CNT' int(11) NOT NULL,
    `DEL_CHK` varchar(1) NOT NULL DEFAULT 'N', `CREA_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `CREA_ID` varchar(30) NOT NULL,  PRIMARY KEY (`IDX`)
)   ENGINE=InnoDB DEFAULT CHARSET=utf8

